Add en locales
Stacha-dev/admin pull request #11
Opened 2021-04-16 07:26 UTC by oliverstasa

translation for admin

2021-04-16 08:21 UTC, pchalupa requested changes

2021-04-16 08:21 UTC, pchalupa commented on public/locales/en/hook.json
> +
Please remove empty line

2021-04-17 06:41 UTC, oliverstasa commented on public/locales/en/hook.json
> +
"upload"?

2021-04-17 06:42 UTC, oliverstasa commented on public/locales/en/hook.json
> +
oh you meen the blank line!

2021-04-17 15:09 UTC, pchalupa requested changes
Please fix typos

2021-04-17 15:09 UTC, pchalupa commented on public/locales/en/page.json
> +		"content": "Contect",
Fix typo
```suggestion
		"content": "Content",
```

2021-04-17 15:09 UTC, pchalupa commented on public/locales/en/page.json
> +		"welcomeBack": "Wellcome back!"
Fix typo
```suggestion
		"welcomeBack": "Welcome back!"
```

2021-04-18 07:53 UTC, pchalupa commented on public/locales/en/page.json
> +		"logIn": "Login",
Watch out! This was changed https://github.com/Stacha-dev/tardis-cms/blob/1d52abce17bf337cb04cc40b5e9177b45bd4305e/public/locales/cs/page.json#L6

2021-04-18 08:56 UTC, pchalupa approved these changes

2021-04-18 08:57 UTC, merged